# Generated by Django 5.2.11 on 2026-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKOUT_INITIATED', 'Checkout Initiated'), ('PAYMENT_PENDING', 'Payment Pending'), ('CHECKED_OUT', 'Checked Out'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30),
        ),
    ]
